### PR TITLE
Do not cancel one-time spot requests

### LINKED ISSUE #11: Don't unnecessarily cancel spot instance requests
The default type of spot instance request is [one-time](https://rusoto.github.io/rusoto/rusoto_ec2/struct.RequestSpotInstancesRequest.html#structfield.type_), which means that you shouldnt need to cancel it once it was created -- it will only be fulfilled once.

### PR DESCRIPTION
**Pull request by freshstrangemusic**
The default behaviour of the spot instance request API is to issue a
one-time request so they do not have to be cancelled afte rthey are
fufilled.

Fixes #11

### CODE REVIEW

**Comment by jonhoo** [comment]
Just for clarification, can you also specifically set the spot instance request type to `one-time` in https://github.com/brennie/tsunami/blob/f75ca3591064561ec164d7b50100f38033962177/src/lib.rs#L343, along with a comment saying "so we don't have to explicitly cancel the request"?

**Comment by jonhoo** [comment]
I think specifically you [have to set](https://rusoto.github.io/rusoto/rusoto_ec2/struct.RequestSpotInstancesRequest.html#structfield.type_):
```rust
req.type_ = Some("one-time".to_string());
```
It'd be nice if this used an enum or something instead of a string, but we'll work with what we've got :)

**Comment by freshstrangemusic** [comment]
Done & done.

**Comment by jonhoo** [comment]
I think you accidentally got rid of the part of the commit that removes the spot request cancellation. Your changes now *only* sets `one-time`, but does *not* remove the cancellation request :)

**Comment by freshstrangemusic** [comment]
Oops!

**Comment by freshstrangemusic** [comment]
Not sure how I pulled that one off :P But It's been updated with both changes now.

**Comment by jonhoo** [comment]
Great, thanks!

**Pull request merged**
